config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  root to: 'items#index'
  get 'items/search'
  resources :users do
    member do
      get 'likes'
    end
  end
  get '/mypage' => 'users#mypage'
  
  resources :items do
    collection do
      get 'recommend'
    end
    collection do
      get 'category_seach'
    end
    collection do
      get 'category_all'
    end
    collection do
      get 'education'
    end
    collection do
      get 'appliances'
    end
    collection do
      get 'cosmetics'
    end
    collection do
      get 'fashion'
    end
    collection do
      get 'food'
    end
    collection do
      get 'hobby'
    end
  end
  resources :items do
    resources :orders, only: [:create, :index]
  end
  resources :items do
    resources :comments, only: :create
  end
  resources :items do
    resource :likes, only: [:create, :destroy]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
          
  has_many :items
  has_many :comments, dependent: :destroy
  has_many :sns_credentials
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item

  validates :nickname, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :email, uniqueness: { case_sensitive: true }

  with_options on: :create? do
    validates :password, presence: true,format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: '半角英数字を使用してください' }
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create

    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:mypage, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update,:likes]

  def index
    redirect_to user_path(current_user)
  end

  def show
    @items = @user.items
  end

  def edit
  end

  def update
    if  @user.update(user_params)
        redirect_to root_path
    else
        redirect_to edit_user_path(current_user)
    end
  end
  
  def likes
    @item = Item.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname,:email,:password,:encrypted_password,)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='account-page mastheadx'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
    <p class="font-weight-bold h1">Edit Account</p>
      <p class="font-weight-bold h5">アカウントの編集</p>
      <%= link_to "ログアウト",  destroy_user_session_path, method: :delete,class: 'btn'%>
      <%= link_to "メインページに戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
      <div class='field'>
          <div class='field-label'>
          <div class="font-weight-bold h5">
            <%= f.label :nickname %>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
          <div class="font-weight-bold h5">
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
          <div class="font-weight-bold h5">
            <%= f.label :password %>
          </div>
          <div class='field-input'>
            <%= f.text_field :password, autofocus: true%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<!doctype html>
<html lang="ja" >
  <head>
    <title>アルバムサンプル for Bootstrap · Bootstrap</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link href="album.css" rel="stylesheet">
    <link href="../example.css" rel="stylesheet">
  </head>

  <body >
    <a id="skippy" class="sr-only sr-only-focusable" href="#content">
      <div class="container">
        <span class="skiplink-text">Skip to main content</span>
      </div>
    </a>

    <header>
    
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container"> 
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">みるポチについて</h4>
          <p class="text-muted">動画を見て気に入った商品があればその場ですぐにポチれる！その商品のイメージを動画で見てお買い物が出来るECサイトです<br>手軽に詳しく気になるものをチェック！動画を見てすぐクリック。自分が見て想像したままのアイテムがすぐ手の中に！</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <!-- <li><a href="#" class="text-white">Follow on Twitter</a></li> -->
            <li><a href="/items/new" class="text-white">動画投稿</a></li>
            <!-- <li><a href="#" class="text-white">Like on Facebook</a></li> -->
            <li><a href="/items/category_all" class="text-white">動画一覧</a></li>
            <!-- <li><a href="#" class="text-white">Email me</a></li> -->
            <li><a href="/items" class="text-white">TOPページに戻る</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <div class="d-flex align-items-center">
        <%=image_tag "portfolio/fullsize/26.png"%>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main role="main">

  <section class="jumbotron text-center mark-food">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">いいね一覧</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="/users" class="btn btn-primary my-2">マイページへ</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
</main>

<ul class='item-lists d-flex'>
  <% @likes.each do |like| %>
    <li class='list col-md-3 mb-3 shadow-sm'>
      <div class= 'item-contents'>
        <% if like.item.video.attached? %>
          <video src="<%= rails_blob_path(like.item.video) %>" type="video/mp4" width="150" height="150" controls></video>
            <span>出品者のチャンネル情報</span> 
            <span>なし</span> 

        <% else %>
          <iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" frameborder="0"src="https://www.youtube.com/embed/<%= like.item.youtube_url.last(11)%>"  allowfullscreen ></iframe>
            <span>出品者のチャンネル情報</span> 

        <div class="url">
          <%= raw Rinku.auto_link like.item.channel, :all, 'target="_blank"rel="noopener noreferrer"'%>
        </div>

        <% end %>
      </div>
      <div class='item-img-contents-main w-100 d-flex'>
        <div class='item-img-contents w-50'>

          <div class="row">
            <div class="col">
              <%= image_tag like.item.image, class: "item-imgs "%> 
            </div>
          </div>

          <% if like.item.rest_quantity == 0%>
            <div class='sold-out'>
              <span>Sold Out!!</span> 
            </div>
          <%end%> 
        </div>

          <div class='item-show-box w-50'>
            <div class='item-info'>
              <h3 class='item-name w-100 h6 text-center'>
                <%= like.item.name %>
              </h3> 

            <div class='item-price w-100 h6'>
              <span ><%= like.item.price %>円</span>
            </div>

              <div class="btn-groupss">
                  
          <% if user_signed_in? && current_user.id == like.item.user_id %>
              <% unless like.item.user_item && like.item.rest_quantity == 0 %>
                  <%= link_to(edit_item_path(like.item.id), method: :get, class: "item-red-btn") do%>
                  <button type="button" class="btn btn-lg btn-block btn-outline-secondary">編集</button>
                  <% end %>
                  <br>
                  <%= link_to(item_path(like.item.id), method: :delete, class:'item-destroy') do%>
                  <button type="button" class="btn btn-lg btn-block btn-danger">削除</button>
                  <% end %>
              <%end%> 

                  <%else%>

            <% unless like.item.user_item && like.item.rest_quantity == 0 %>
                  <%= link_to(item_orders_path(like.item.id), method: :get, class: "item-red-btn") do%>
                  <button type="button" class="btn btn-lg btn-block btn-danger">購入</button>
                  <% end %>
                  <br>
                  <%= link_to(item_path(like.item.id), method: :get, class: "item-red-btn") do%>
                  <button type="button" class="btn btn-lg btn-block btn-outline-secondary">詳細</button>
                  <% end %>
                  </div>
            <%end%>
          <%end%>

                  <div class="main_contents">
                    <div class="text-center" id="likes_buttons_<%= like.item.id %>">
                      <% if user_signed_in? %>
                      <% if like.item.liked_by?(current_user) %>
                      <p><span>❤︎: </span><%=link_to like.item.likes.count, item_likes_path(like.item.id), method: :delete, remote: true %></p>
                      <% else %>
                      <p><span>❤︎: </span><%=link_to like.item.likes.count, item_likes_path(like.item.id), method: :post , remote: true %></p>
                      <% end %>
                      <% else %>
                      <p><span>❤︎: </span><%= like.item.likes.count %></p>
                      <% end %>

                    </div>
                  </div>

                  <div class='h6 text-center'>
                  <span>残り<%=like.item.rest_quantity%>個</span>
                  </div> 
        
      </div>
    </li>
  <%end%>
</ul>
<script src="../../assets/js/vendor/holder.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery-slim.min.js"><\/script>')
</script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script><script src="/docs/4.5/assets/js/vendor/anchor.min.js"></script>
<script src="/docs/4.5/assets/js/vendor/clipboard.min.js"></script>
<script src="/docs/4.5/assets/js/vendor/bs-custom-file-input.min.js"></script>
<script src="/docs/4.5/assets/js/src/application.js"></script>
<script src="/docs/4.5/assets/js/src/search.js"></script>
<script src="/docs/4.5/assets/js/src/ie-emulation-modes-warning.js"></script>
  </body>
</html>

app/views/users/show.html.erb
<body>
<ul class='item-lists d-flex'>
  <div class="row">
    <div class="col-lg-3">

      <h5 class="my-4 text-center"><%= @user.nickname  %>MY動画ページ</h5>
      <div class="list-group">
        <% if user_signed_in? && @user == current_user %>
        <%= link_to "プロフィール編集", edit_user_registration_path, class: "list-group-item" %>
        <% end %>
        <%= link_to "いいねした商品",  likes_user_path(current_user.id), class: "list-group-item"%>
        <%= link_to "動画投稿", new_item_path, class: "list-group-item"%>
        <%= link_to "動画検索", category_seach_items_path, class: "list-group-item"%>
        <%= link_to "戻る", root_path, class: "list-group-item"%>
      </div>

    </div>

      <div class="col-lg-9">
        <div class="my-4 mx-4">
          <%=image_tag "portfolio/fullsize/8.png", class:"d-block img-fluid mt-5",size:"825x300"%>
        </div>
      </div>
      <%= render 'items/form', items: @items %>
      </div>
  </div>
</ul>
</body>