config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  root to: 'items#index'
  get 'items/search'
  resources :users do
    member do
      get 'likes'
    end
  end
  get '/mypage' => 'users#mypage'
  
  resources :items do
    collection do
      get 'recommend'
    end
    collection do
      get 'category_seach'
    end
    collection do
      get 'category_all'
    end
    collection do
      get 'education'
    end
    collection do
      get 'appliances'
    end
    collection do
      get 'cosmetics'
    end
    collection do
      get 'fashion'
    end
    collection do
      get 'food'
    end
    collection do
      get 'hobby'
    end
  end
  resources :items do
    resources :orders, only: [:create, :index]
  end
  resources :items do
    resources :comments, only: :create
  end
  resources :items do
    resource :likes, only: [:create, :destroy]
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_one :user_item
  belongs_to :user
  has_one_attached :image
  has_one_attached :video

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  with_options presence: true do
    validates :name
    validates :content
    validates :shipping_cost_id
    validates :shipping_day_id
    validates :prefecture_id
    validates :category_id
    validates :image
    validates :quantity
  end

  validates_inclusion_of :price, in: 300..9_999_999
  with_options presence: true, format: { with: /\A[0-9]+\Z/ } do
    validates :price
  end

  
  belongs_to_active_hash :category
  belongs_to_active_hash :shipping_cost
  belongs_to_active_hash :shipping_day
  belongs_to_active_hash :prefecture

  validate :image_presence
  validates :youtube_url, format: { with: /\A(https\:\/\/)?(www\.)?(youtube\.com\/watch\?v=|youtu\.be\/)+[\S]{11}\z/ , message: 'を入力してください'},allow_blank: true
  validates :category_id, :shipping_cost_id, :shipping_day_id, :prefecture_id, numericality: { other_than: 1 }
  # validate :required_either_email_or_phone
  


  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def image_presence
    if image.attached?
      if !image.content_type.in?(%('image/jpeg image/png'))
        errors.add(:image, 'にはjpegまたはpngファイルを添付してください')
      end
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end

  private

  def required_either_email_or_phone

    return if youtube_url.present? ^ video.present?

    errors.add(:base, 'YOUTUBE,URLまたは動画のどちらか一方を入力してください')
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :education ,:appliances, :fashion, :cosmetics, :food, :hobby, :recommend, :show, :search, :category_seach, :category_all]
  before_action :set_item, only: [:edit, :update, :destroy, :show]
  before_action :direct_index, only: [:edit, :destroy]
  before_action :search_item, only: [:category_seach, :search]
  

  def index
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.assign_attributes(rest_quantity: item_params[:quantity])
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def update
    if @item.user_id == current_user.id
      if @item.update(item_params)
        redirect_to root_path
      else
        redirect_to action: :edit
      end
    else
      redirect_to action: :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def recommend
    @items = Item.includes(:user_item).where.not(rest_quantity: 0).sort{|a,b| b.liked_users.count <=> a.liked_users.count}
  end

  def search
    @q = Item.ransack(params[:q])
    @results = @q.result
  end

  def category_seach
    @q = Item.ransack(params[:q])
    @items = Item.all
    set_item_column
  end

  def category_all
    @items = Item.order('created_at DESC').where("category_id")
  end

  def education
    @items = Item.order('created_at DESC').where("category_id=2")
  end

  def appliances
    @items = Item.order('created_at DESC').where("category_id=3")
  end

  def fashion
    @items = Item.order('created_at DESC').where("category_id=4")
  end

  def cosmetics
    @items = Item.order('created_at DESC').where("category_id=5")
  end

  def food
    @items = Item.order('created_at DESC').where("category_id=6")
  end

  def hobby
    @items = Item.order('created_at DESC').where("category_id=7")
  end 




  private

  def item_params
    params.require(:item).permit(:channel, :video, :quantity, :text, :youtube_url, :image, :name, :content, :category_id, :shipping_cost_id, :shipping_day_id, :prefecture_id, :price).merge(user_id: current_user.id)
  end
  def set_item
    @item = Item.find(params[:id])
  end

  def direct_index
    redirect_to root_path unless current_user.id == @item.user_id
  end

  def search_item
    @p = Item.ransack(params[:q]) 
  end

  def set_item_column
    @item_name = Item.select("name").distinct
  end

end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_bootstrap_fotter.html.erb
<script src="../../assets/js/vendor/holder.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery-slim.min.js"><\/script>')
</script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script><script src="/docs/4.5/assets/js/vendor/anchor.min.js"></script>
<script src="/docs/4.5/assets/js/vendor/clipboard.min.js"></script>
<script src="/docs/4.5/assets/js/vendor/bs-custom-file-input.min.js"></script>
<script src="/docs/4.5/assets/js/src/application.js"></script>
<script src="/docs/4.5/assets/js/src/search.js"></script>
<script src="/docs/4.5/assets/js/src/ie-emulation-modes-warning.js"></script>
  </body>
</html>

app/views/items/_category_heder.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container"> 
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">みるポチについて</h4>
          <p class="text-muted">動画を見て気に入った商品があればその場ですぐにポチれる！その商品のイメージを動画で見てお買い物が出来るECサイトです<br>手軽に詳しく気になるものをチェック！動画を見てすぐクリック。自分が見て想像したままのアイテムがすぐ手の中に！</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <!-- <li><a href="#" class="text-white">Follow on Twitter</a></li> -->
            <li><a href="/items/new" class="text-white">動画投稿</a></li>
            <!-- <li><a href="#" class="text-white">Like on Facebook</a></li> -->
            <li><a href="/items/category_all" class="text-white">動画一覧</a></li>
            <!-- <li><a href="#" class="text-white">Email me</a></li> -->
            <li><a href="/items" class="text-white">TOPページに戻る</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <div class="d-flex align-items-center">
        <%=image_tag "portfolio/fullsize/26.png"%>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/items/appliances.html.erb
<%= render 'bootstrap', item: @item %>
<%= render 'category_heder', item: @item %>

    <main role="main">
      <section class="jumbotron text-center mark-appliances">
        <div class="container">
          <!-- <h1 class="jumbotron-heading">Album example</h1> -->
          <h1 class="jumbotron-heading">家電 appliances</h1>
          <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
          <br>
          <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
          <a href="/items/fashion" class="btn btn-primary my-2">次のジャンルへ</a>
          <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
          <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
        </div>
      </section>
    </main>

    <%= render 'form', item: @item %>

    <footer class="text-muted">
    </footer>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>
    window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery-slim.min.js"><\/script>')
    </script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script><script src="/docs/4.5/assets/js/vendor/anchor.min.js"></script>
    <script src="/docs/4.5/assets/js/vendor/clipboard.min.js"></script>
    <script src="/docs/4.5/assets/js/vendor/bs-custom-file-input.min.js"></script>
    <script src="/docs/4.5/assets/js/src/application.js"></script>
    <script src="/docs/4.5/assets/js/src/search.js"></script>
    <script src="/docs/4.5/assets/js/src/ie-emulation-modes-warning.js"></script>
  </body>
</html>

app/views/items/category_all_html.erb
<!doctype html>
<html lang="ja" >
  <head>
    <title>アルバムサンプル for Bootstrap · Bootstrap</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link href="album.css" rel="stylesheet">
    <link href="../example.css" rel="stylesheet">
  </head>
  <body >
    <a id="skippy" class="sr-only sr-only-focusable" href="#content">
  <div class="container">
    <span class="skiplink-text">Skip to main content</span>
  </div>
</a>

<%= render 'category_heder', item: @item %>

<main role="main">

  <section class="jumbotron text-center mark-category">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">動画一覧</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="#" class="btn btn-primary my-2">次のジャンルへ</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
</main>

<%= render 'form', item: @item %>

<footer class="text-muted">

</footer>
<script src="../../assets/js/vendor/holder.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery-slim.min.js"><\/script>')
</script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script><script src="/docs/4.5/assets/js/vendor/anchor.min.js"></script>
<script src="/docs/4.5/assets/js/vendor/clipboard.min.js"></script>
<script src="/docs/4.5/assets/js/vendor/bs-custom-file-input.min.js"></script>
<script src="/docs/4.5/assets/js/src/application.js"></script>
<script src="/docs/4.5/assets/js/src/search.js"></script>
<script src="/docs/4.5/assets/js/src/ie-emulation-modes-warning.js"></script>
  </body>
</html>

app/views/items/category_seach.erb
<div class="page-sections bg-primary mastheads flex-column ">
  <h1 class="mx-auto text-center font-weight-bold text-white" style="width: 800px;">MOVIE SEARCH SCREEN
    <br>
  <h1 class="text-white font-weight-bold text-center">CHECK THE KEYWORDS YOU CARE ABOUT</h1>
  <%=link_to 'TOPへ戻る', root_path, class:"btn btn-primary mx-auto" %>
  </h1>
</div>
      
      <div class="search-contents d-flex align-items-center">
          <div class="containers">
          <div class="page-sectionss bg-primary">
      </div>
          
          <%= search_form_for @q, url: items_search_path do |f| %>
            <br>
      <div class="font-weight-bold h1 text-center ">動画検索機能</div>
            <br>
            <br>
            <br>
          <div class="font-weight-bold h5 mx-5">
              <%= f.label :name_cont, "商品名" %>
              <%= f.text_field :name_cont %>
          </div>
          <br>

          <div class="font-weight-bold h5 mx-5">
              <%= f.label :category_id_eq, 'カテゴリー：' %>
              <%= f.select :category_id_eq, [["教育", 2], ["家電", 3], ["ファッション", 4], ["コスメ", 5],["グルメ", 6], ["ホビー", 7]], include_blank: "選択して下さい" %>
          </div>
          <br>

          <div class="font-weight-bold h5 mx-5">
            <%= f.label :shipping_day_id_eq, 'お届け日数：' %> 
            <%= f.select :shipping_day_id_eq,[["1~2日で発送", 2], ["2~3日で発送", 3],["4~7日で発送",4]] , include_blank: '指定なし' %>
          </div>
          <br>

          <div class="font-weight-bold h6 mx-5">
            <%= f.label :price %>
            <%= f.number_field :price_gteq, min: 1%>以上 ~
            <%= f.number_field :price_lteq, min: 1%>以下
          </div>
          <br>

          <%= f.submit class: 'btn btn-primarys mx-5' %>
          <% end %>
          <br>    
          <div class="page-sectionsss bg-primary">
          </div>
      </div>

app/views/items/cosmetics.html.erb
<%= render 'bootstrap', item: @item %>
<%= render 'category_heder', item: @item %>

<main role="main">

  <section class="jumbotron text-center mark-cosmetics">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">コスメ cosmetics</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="/items/food" class="btn btn-primary my-2">次のジャンルへ</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
</main>

<%= render 'form', item: @item %>

<footer class="text-muted">

</footer>
<%= render 'bootstrap_fotter',item: @item %>

app/views/items/education.html.erb
<%= render 'bootstrap', item: @item %>
<%= render 'category_heder', item: @item %>

<main role="main">

  <section class="jumbotron text-center mark-up">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">教育 education</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="/items/appliances" class="btn btn-primary my-2">次のジャンルへ</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
</main>

<%= render 'form', item: @item %>

<footer class="text-muted">

</footer>
<%= render 'bootstrap_fotter',item: @item %>

app/views/items/fashion.html.erb
<%= render 'bootstrap', item: @item %>
<%= render 'category_heder', item: @item %>

<main role="main">

  <section class="jumbotron text-center mark-fashion">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">ファッション fashion</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="/items/cosmetics" class="btn btn-primary my-2">次のジャンルへ</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
</main>

<%= render 'form', item: @item %>

<footer class="text-muted">

</footer>
<%= render 'bootstrap_fotter',item: @item %>

app/views/items/food.html.erb
<%= render 'bootstrap', item: @item %>
<%= render 'category_heder', item: @item %>

<main role="main">

  <section class="jumbotron text-center mark-food">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">フード food</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="/items/hobby" class="btn btn-primary my-2">次のジャンルへ</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
</main>

<%= render 'form', item: @item %>

<footer class="text-muted">

</footer>
<%= render 'bootstrap_fotter',item: @item %>

app/views/items/hobby.html.erb
<%= render 'bootstrap', item: @item %>
<%= render 'category_heder', item: @item %>

<main role="main">

  <section class="jumbotron text-center mark-orange">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">ホビー hobby</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="/items/education" class="btn btn-primary my-2">次のジャンルへ</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
</main>

<%= render 'form', item: @item %>

<footer class="text-muted">

</footer>
<%= render 'bootstrap_fotter',item: @item %>

app/views/items/recommend.html.erb
<%= render 'bootstrap', item: @item %>
<%= render 'category_heder', item: @item %>

  <main role="main">

    <section class="jumbotron text-center mark-category">
      <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">オススメ一覧</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="/items/category_seach" class="btn btn-primary my-2">商品検索</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
      </div>
    </section>
  </main>
  <%= render 'form', item: @item %>
  <%= render 'footer'%>
  <script src="../../assets/js/vendor/holder.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>
  window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery-slim.min.js"><\/script>')
</script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script><script src="/docs/4.5/assets/js/vendor/anchor.min.js"></script>
<script src="/docs/4.5/assets/js/vendor/clipboard.min.js"></script>
<script src="/docs/4.5/assets/js/vendor/bs-custom-file-input.min.js"></script>
<script src="/docs/4.5/assets/js/src/application.js"></script>
<script src="/docs/4.5/assets/js/src/search.js"></script>
<script src="/docs/4.5/assets/js/src/ie-emulation-modes-warning.js"></script>
  </body>
</html>

app/views/items/search.html.erb
<%= render 'bootstrap', item: @item %>
  <%= render 'category_heder', item: @item %>

  <main role="main">
  <section class="jumbotron text-center mark-orange">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">検索結果</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <br>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <a href="/items/category_seach" class="btn btn-primary my-2">検索画面へ</a>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%=link_to 'TOPへ戻る', root_path, class:"btn btn-secondary my-2" %>
      </p>
    </div>
  </section>
  </main>


  <% if @results.any? %>
  <ul class='item-lists'>
    <% @results.each do |result|  %>
      <li class='list col-md-3 mb-3 shadow-sm'>
      <div class= 'item-contents'>

          <% if result.video.attached? %>
            <video src="<%= rails_blob_path(result.video) %>" type="video/mp4" width="150" height="150" controls></video>
            <span>出品者のチャンネル情報</span> 
            <span>なし</span> 
          <% else %>
          <iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" frameborder="0"src="https://www.youtube.com/embed/<%= result.youtube_url.last(11)%>"  allowfullscreen ></iframe>
          <span>出品者のチャンネル情報</span> 
          <div class="url">
          <%= raw Rinku.auto_link result.channel, :all, 'target="_blank"rel="noopener noreferrer"'%>
          </div>
          <% end %>
        </div>
          <div class='item-img-contents-main w-100 d-flex'>
            <div class='item-img-contents w-50'>
              <div class="row">
                <div class="col">
                  <%= image_tag result.image, class: "item-imgs "%> 
                  <% if result.rest_quantity == 0%>
                  <div class='sold-out'>
                  <span>Sold Out!!</span> 
                </div>
                <%end%> 
              </div>
            </div>
          </div>

          <div class='item-show-box w-50'>
            <div class='item-info'>
              <h3 class='item-name w-100 h6 text-center'>
              <%= result.name %>
              </h3> 

            <div class='item-price w-100 h6'>
              <span ><%= result.price %>円</span>
            </div>

            <div class="btn-groupss">
            <% if user_signed_in? && current_user.id == result.user_id %>
              <% unless result.user_item && result.rest_quantity == 0 %>
                  <%= link_to(edit_item_path(result.id), method: :get, class: "item-red-btn") do%>
                  <button type="button" class="btn btn-lg btn-block btn-outline-secondary">編集</button>
                  <% end %>
                  <br>
                  <%= link_to(item_path(result.id), method: :delete, class:'item-destroy') do%>
                  <button type="button" class="btn btn-lg btn-block btn-danger">削除</button>
                  <% end %>
              <%end%>

                  <%else%>

              <% unless result.user_item && result.rest_quantity == 0%>
                  <%= link_to(item_orders_path(result.id), method: :get, class: "item-red-btn") do%>
                  <button type="button" class="btn btn-lg btn-block btn-danger">購入</button>
                  <% end %>
                  <br>
                  <%= link_to(item_path(result.id), method: :get, class: "item-red-btn") do%>
                  <button type="button" class="btn btn-lg btn-block btn-outline-secondary">詳細</button>
                  <% end %>
                  </div>
              <%end%>
            <%end%>

            <div class="main_contents">
              <div class="text-center" id="likes_buttons_<%= result.id %>">
                  <% if user_signed_in? %>
                  <% if result.liked_by?(current_user) %>
                  <p><span>❤︎: </span><%=link_to result.likes.count, item_likes_path(result.id), method: :delete, remote: true %></p>
                  <% else %>
                  <p><span>❤︎: </span><%=link_to result.likes.count, item_likes_path(result.id), method: :post , remote: true %></p>
                  <% end %>
                  <% else %>
                  <p><span>❤︎: </span><%= result.likes.count %></p>
                  <% end %>
              </div>
            </div>

                  <div class='h6 text-center'>
                  <span>残り<%=result.rest_quantity%>個</span>
                  </div> 
      </div> 
      </li>
  <% end %>
  </ul>
  <% else %>
  <h3 class="jumbotron-heading text-center">該当する商品はありません</h3>
  <% end %>


<%= render 'bootstrap_fotter',item: @item %>